/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package code05;

import org.junit.jupiter.api.Test;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        LinkedList classUnderTest = new LinkedList();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test
    public Void included() throws IOException {
        LinkedList classUnderTest = new LinkedList();
        classUnderTest.add("khair");


        assertTrue(classUnderTest.included("khair"),"this is true ");
        return null;
    }
    @Test void printList(){

        LinkedList classUnderTest = new LinkedList();

        classUnderTest.add("K");
        classUnderTest.add("H");
        classUnderTest.add("A");
        classUnderTest.add("I");
        classUnderTest.add("R");
        assertEquals("Head -> {H}  ->{K}   -> {A}   -> {I}   -> {R}   -> null -> ",classUnderTest.toString(),"app should return ==> Head -> {K}  ->{H}   -> {A}   -> {I}   -> {R}   -> null -> ");

    }

}
